//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAsp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeType
    {
        public int CoffeeTypeId { get; set; }
        public string CountryOfOrigin { get; set; }
        public decimal Price { get; set; }
    }
}
